### ISSUE TITLE
Resources in "webapp" folder are not processed

### ISSUE THREAD

**Issue by sproskurnya** [guillermo-varela/gradle-replace-properties-resources-plugin#1]
Tokens are replaced only for resources from "main/resources" folder.
Token replacement is not working for resources in "main/webapp" folder, for example for "main/webapp/WEB-INF/web.xml".

**Comment by guillermo-varela** [comment]
@sproskurnya: The current code only looks at the "resources" declared on each "source set": https://github.com/guillermo-varela/gradle-replace-properties-resources-plugin/blob/master/src/main/groovy/com/blogspot/nombre_temp/gradle/replace/properties/resources/ReplacePropertiesResourcesPlugin.groovy#L51

Therefore, it won't replace anything on anyother folder.
Pull-requests are welcome of course :)
